// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-F62kWOQe_Km4-0i6v8MjC0uF74T7F1c',
    appId: '1:7655683762:web:e5cb5bd95f29569685fbab',
    messagingSenderId: '7655683762',
    projectId: 'ceylon-travel-mvp',
    authDomain: 'ceylon-travel-mvp.firebaseapp.com',
    storageBucket: 'ceylon-travel-mvp.firebasestorage.app',
    measurementId: 'G-1JDP28RV0Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAY6icMoE0RVyzpIQPBvIFJUFues9mbb4E',
    appId: '1:7655683762:android:fee391366839d10185fbab',
    messagingSenderId: '7655683762',
    projectId: 'ceylon-travel-mvp',
    storageBucket: 'ceylon-travel-mvp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOtqHlWBVo37-fXefRMPmT3nO-exiuwYA',
    appId: '1:7655683762:ios:4d8fd3e35550ac2985fbab',
    messagingSenderId: '7655683762',
    projectId: 'ceylon-travel-mvp',
    storageBucket: 'ceylon-travel-mvp.firebasestorage.app',
    iosBundleId: 'com.example.taxiApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOtqHlWBVo37-fXefRMPmT3nO-exiuwYA',
    appId: '1:7655683762:ios:4d8fd3e35550ac2985fbab',
    messagingSenderId: '7655683762',
    projectId: 'ceylon-travel-mvp',
    storageBucket: 'ceylon-travel-mvp.firebasestorage.app',
    iosBundleId: 'com.example.taxiApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-F62kWOQe_Km4-0i6v8MjC0uF74T7F1c',
    appId: '1:7655683762:web:361ba229778ca07585fbab',
    messagingSenderId: '7655683762',
    projectId: 'ceylon-travel-mvp',
    authDomain: 'ceylon-travel-mvp.firebaseapp.com',
    storageBucket: 'ceylon-travel-mvp.firebasestorage.app',
    measurementId: 'G-3KKF217B15',
  );
}
